name: meta-kaggle
channels:
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python=3.11
  - pip

  # Data processing
  - polars>=0.19.0
  - duckdb>=0.9.0
  - pyarrow>=13.0.0
  - pandas>=2.0.0

  # Parallel processing
  - ray-core>=2.6.0

  # Graph analytics
  - networkx>=3.0

  # Visualization
  - plotly>=5.10.0
  - dash>=2.8.0
  - scipy>=1.10.0

  # Development tools
  - pytest>=7.0.0
  - black>=23.0.0
  - ruff>=0.0.265
  - mypy>=1.0.0
  - pre-commit>=3.0.0

  # Using pip for packages not well-supported in conda
  - pip:
    - sentence-transformers>=2.2.0
    - bertopic>=0.14.0
    - lifelines>=0.27.0
    - statsmodels>=0.13.0
    - prophet>=1.1.0
    - radon>=5.1.0
    - pymannkendall>=1.4
    - kedro>=0.18.0
    - pytest-cov>=4.0.0
    - kedro-datasets
