# Parameters for Meta Kaggle project

# ETL parameters
# etl:
#   src_dir: "data/raw_csv"
#   dst_dir: "data/parquet/raw"
#   intermediate_dir: "data/intermediate"
#   mini_meta_dir: "data/mini_meta"
#   sample_frac: 0.01
#   tables:
#     KernelVersions: "CreationDate"
#     Competitions: "DeadlineDate"
#     Datasets: "CreationDate"
#     Users: "RegisterDate"
#     ForumMessages: "PostDate"
#     Kernels: null
#     KernelTags: null
#     Tags: null
#     CompetitionTags: null
#     KernelVersionCompetitionSources: null
#     KernelVersionDatasetSources: null
#     Teams: "LastSubmissionDate"
#     TeamMemberships: "RequestDate"
#     Submissions: "SubmissionDate"
#     ForumTopics: "CreationDate"
#     DatasetVersions: "CreationDate"
#     DatasetVotes: "VoteDate"
#     UserAchievements: "TierAchievementDate"
#     UserOrganizations: "JoinDate"
#     Organizations: "CreationDate"

data_layer:
  src_dir: data/raw_csv
  dst_dir: data/parquet/raw
  output_dir: data/intermediate
  pruned_output_path: data/intermediate/kernel_bigjoin_clean.parquet
  mini_meta_dir: "data/mini_meta"
  sample_frac: 0.01
  tables:
    KernelVersions: "CreationDate"
    Competitions: "DeadlineDate"
    Datasets: "CreationDate"
    Users: "RegisterDate"
    ForumMessages: "PostDate"
    Kernels: null
    KernelTags: null
    Tags: null
    CompetitionTags: null
    KernelVersionCompetitionSources: null
    KernelVersionDatasetSources: null
    Teams: "LastSubmissionDate"
    TeamMemberships: "RequestDate"
    Submissions: "SubmissionDate"
    ForumTopics: "CreationDate"
    DatasetVersions: "CreationDate"
    DatasetVotes: "VoteDate"
    UserAchievements: "TierAchievementDate"
    UserOrganizations: "JoinDate"
    Organizations: "CreationDate"
    KernelAcceleratorTypes: ~

features:
  local_code_root: "data/raw_code"
  output_dir: "data/intermediate"
  processed_dir: "data/processed"
  metadata_path: "data/intermediate/kernel_bigjoin_clean.parquet"
  embedding_model: "all-MiniLM-L6-v2"
  batch_size: 400
  sample_size: 0
  keep_embeddings: false

graphs:
  output_dir: "data/graph"
  visuals_dir: "visuals/graphs"
  node_limit: 500
  pagerank_alpha: 0.85
  time_decay_hours: 168  # 7 days
  libraries_to_analyze:
    - "gbdt"
    - "dl_pytorch"
    - "dl_tf"
    - "auto_ml"
